#!/bin/bash
# WARNING: have a backup of your minecraft.jar at hand!
# This script overwrites the minecraft.jar.

rm -rf minecraft-tmp/*
cp ~/Library/Application\ Support/minecraft/bin/minecraft.jar minecraft-tmp/minecraft.jar
cd minecraft-tmp
unzip -d minecraft minecraft.jar
rm -rf minecraft/META-INF/CODESIGN*

# Get the right stuff from Forge
unzip -d MinecraftForge ~/Desktop/mods/MinecraftForge*
mv MinecraftForge/paulscode paulscode
cp -Rf MinecraftForge/ minecraft/
cp paulscode/sound/codecs/CodecIBXM.class minecraft/paulscode/sound/codecs/

# PlayerAPI
unzip -d PlayerAPI ~/Desktop/mods/MC\ 1.2.5\ -\ Player\ API\ client\ 1.5.zip
cp -Rf PlayerAPI/ minecraft/

# Aether
unzip -d aether ~/Desktop/mods/aether_1.9.zip
mv aether/Jar/armor armor
mv aether/Resources Resources
cp -Rf aether/Jar/ minecraft/
cp armor/* minecraft/armor
cp -Rf Resources minecraft/Resources

mv minecraft.jar old-minecraft.jar

cd minecraft
zip -r ../minecraft.jar .
cd ..

# now the install...
cp -f minecraft.jar ~/Library/Application\ Support/minecraft/bin/


 
